### ISSUE TITLE
Change reviews to comments and add review to schema for pins

### ISSUE THREAD

**Issue by james-woo** [fridayideas/daytomatoserver#20]
Instead of reviews for pins, it should be comments. However, we still need a review attribute in the pins schema. Please add it!

e.g.
pins {
  "review" : "review",
  "comments" : ["comments"]
}

**Comment by ToucheSir** [comment]
There needs to be a discussion about this. I'll hold off on reverting the PR for now, though.

**Comment by james-woo** [comment]
What's wrong about this?

**Comment by ToucheSir** [comment]
Hazy on the value proposition behind this change, and it doesn't appear we went over this design change/decision.

**Comment by james-woo** [comment]
Initially, we were going to add reviews to pins, where people can review pins. But there was an issue of what about the owners pin, how do they place a review, stick it in the reviews array? Splitting this up and renaming them solves this issue. Its really the same thing, just different wording and separation of the owner and users.

**Comment by ToucheSir** [comment]
Again, we should have an in-depth group discussion about this.

**Comment by ryansama** [comment]
Hey all, so I just talked this through with James and I think I can clarify this now. 

Let's say we have some location, for example Jam Cafe. I can place my own pin on Jam Cafe. I create this pin by providing price range, my own rating (out of 5 stars), and my **own review** of Jam Cafe, for example, _"This place has great servce and great food"_. My pin can be upvoted or downvoted upon by others. My review is the main focus of my pin.

Once created, this pin will also have a comments section under it (initially hidden but expandable). Others who view my pin can comment **their thoughts about my pin**. For example, James can comment _"I disagree about your price range because I think this place is more on the expensive side"_. If I wanted to, I can take his comment into consideration and modify my pin to adjust the price range. 

This comments feature is something very small and can be removed if needed. The comments on a pin are initially hidden when people view all the pins for Jam Cafe. The comments have no direct effect on the pin. You can just think of them as lines of text. 

I think the confusion about this Issue(#20) is that initially we had a "reviews" array within the pin. This should have been called "comments".

**Comment by ToucheSir** [comment]
Reached consensus what information should be in pins. Closing this now.
